version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - backend
    restart: always
    entrypoint: ["/bin/sh", "-c", "/app/entrypoint.sh"]
    volumes:
      - client_dist:/app/dist # Общий volume для копирования файлов
    healthcheck:
      test:
        [
          "CMD",
          "test",
          "-f",
          "/app/dist/client2/browser/product/679dd4f6dd24a0f6b7579b08/index.html",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - "/etc/letsencrypt:/etc/letsencrypt"
      - client_dist:/usr/share/nginx/html # Файлы попадают в Nginx через volume
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      frontend:
        condition: service_healthy # Ждем, пока frontend подтвердит, что файлы есть
    restart: always

volumes:
  client_dist:
